source/protected/apps/frontend/controllers/FilmController.php
<?php

class FilmController extends Controller
{

    public function actionViewCat()
    {
        // get post
        //$id = Yii::app()->request->getPost(); 
        $id = Yii::app()->getRequest()->getQuery('id');

        if (isset($id)) {
            $criteria = new CDbCriteria();
            $criteria->condition = 'status != ' . File::STATUS_DELETE . ' and category_id = ' . $id;
            $criteria->order = 'created_date DESC';

            $dataProvider = new CActiveDataProvider('Film', array(
                'criteria' => $criteria,
                'pagination' => array(
                    'pageSize' => param('pageSize')
                )
            ));

            $this->render('view_cat', array('dataProvider' => $dataProvider->getData()));
        }
    }

    public function actionSearch()
    {
        $criteria = new CDbCriteria();
        $criteria->order = 'created_date DESC';

        if (isset($_GET['query']) && !empty($_GET['query'])) {
            $query = $_GET['query'];
            $str = explode(" ", $query);
            foreach ($str as $v) {
                $criteria->compare("title", $v, true, 'OR');
                $criteria->compare("director", $v, true, 'OR');
                $criteria->compare("author", $v, true, 'OR');
            }
        }
        else
            $criteria->condition = 'id = 0';

        $dataProvider = new CActiveDataProvider('Film', array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => param('pageSize'),
            )
        ));

        $this->render('index', array('dataProvider' => $dataProvider));
    }

    public function actionIndex()
    {
        $criteria = new CDbCriteria();
        $criteria->condition = 'status != ' . File::STATUS_DELETE;
        $criteria->order = 'created_date DESC';

        $dataProvider = new CActiveDataProvider('Film', array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => param('pageSize')
            )
        ));

        $this->render('index', array('dataProvider' => $dataProvider));
    }

    public function actionView()
    {
        $id = Yii::app()->getRequest()->getQuery('id');

        if (isset($id)) {
            $criteria = new CDbCriteria();
            $criteria->condition = 'status != ' . File::STATUS_DELETE . ' AND id = ' . $id;
            $criteria->order = 'created_date DESC';

            $dataProvider = new CActiveDataProvider('Film', array(
                'criteria' => $criteria,
                'pagination' => array(
                    'pageSize' => param('pageSize')
                )
            ));

            $this->render('view', array('dataProvider' => $dataProvider));
        }
    }

    public function actionWatch()
    {
        $id = Yii::app()->getRequest()->getQuery('id');

        if (isset($id)) {
            $criteria = new CDbCriteria();

            $criteria->condition .= 'status != ' . File::STATUS_DELETE . ' AND id=' . $id;
            $criteria->order = 'created_date DESC';

            $dataProvider = new CActiveDataProvider('Film', array(
                'criteria' => $criteria,
            ));

            $this->render('watch', array('dataProvider' => $dataProvider));
        }
    }

    //url('film/detail', array('id' => 1));
    public function actionDetail($id)
    {
        $film = Film::model()->findByPk($id);
        $this->render('detail', array('model' => $film));
    }

    public function actionDownload()
    {
        $id = Yii::app()->getRequest()->getQuery('id');

        if (isset($id)) {
            $criteria = new CDbCriteria();

            $criteria->condition = ' id=' . $id;
            $dataProvider = new CActiveDataProvider('File', array(
                'criteria' => $criteria,
            ));
            $data = $dataProvider->getData();
            foreach ($data as $file){
                $fPath = $file->source;
                $fExtension = $file->extension;
                $fName = $file->name;
            }
            
            $path = Utils::uploadPath($fPath);

            header("Content-type: {$fExtension}");
            header("Pragma: public"); // required
            header("Expires: 0");
            header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
            header("Cache-Control: private", false); // required for certain browsers
            header("Content-Disposition: attachment; filename=\"" . basename($fName) . "\";");
            header("Content-Transfer-Encoding: binary");
            //header("Content-Length: ".$fileSize);
            ob_clean();
            flush();
            readfile($path);
            exit;
        }
    }

}

source/protected/apps/frontend/controllers/UserController.php
<?php

class UserController extends Controller
{
    public function actionRegister() {
        $model = new RegisterForm();
        $user = new User();
        if (isset($_POST['RegisterForm'])) {

            $model->attributes = $_POST['RegisterForm'];
            if ($model->validate()) {
                $user->attributes = $model->attributes;
                $user->password = $password = randomString(8);
                if ($user->save()) {
                    user()->setFlash('success', $model->email . ' has been created successfully! Check your Email to get your password');
                    $params = array(
                        'to' => array($model->email, $model->email),
                        'data' => array(
                            'EMAIL' => $model->email,
                            'PASSWORD' => $password,
                            'FULLNAME' => $model->first_name . ' ' . $model->last_name,
                        ),
                    );
                    CeresMail::queue('userCreate', $params);
                }
            }
        }

        $this->render('_form_register', array('model' => $model));
    }

    public function actionLogin()
    {
        //var_dump(Utils::md5('123456'));
        //die();
        $model = new LoginForm();
        
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            $model->username = $_POST['LoginForm']['username'];
            
            if ($model->validate() && $model->login())
                $this->redirect(url('/'));
        }
        
        $this->render('login', array('model' => $model));
    }

    public function actionProfile()
    {
        $user = User::model()->findByPk(user()->id);
        
         if (isset($_POST['User'])) {
            $user->attributes = $_POST['User'];
            
            if ($user->save())
                Yii::app()->user->setFlash('success', 'Update profile successfully');
        }
        
        $this->render('profile',array('model' => $user));
    }
    
    public function actionDownLoadHistory()
    {
        $criteria = new CDbCriteria();        
        $criteria->order = 'created_date DESC';
        $criteria->condition = 'user_id = ' . user()->id;
        
        $dataProvider = new CActiveDataProvider('DownloadHistory', array(
            'criteria' => $criteria,
            'pagination' => array(
                'pageSize' => 10
            )
        ));
        
        $this->render('downloadHistory', array('dataProvider' => $dataProvider));
    }
    
    public function actionWatchTrailerHistory()
    {
        $criteria = new CDbCriteria();        
        //$criteria->order = 'created_date DESC';
        $criteria->condition = 'user_id = ' . user()->id;
        
        $dataProvider = new CActiveDataProvider('WatchTrainerHistory', array(
            'criteria' => $criteria,
            'pagination' => array('pageSize' => 10)
        ));
        $this->render('watchTrailerHistory', array('dataProvider' => $dataProvider));
    }
    
    public function actionWatchFullHistory()
    {
        $criteria = new CDbCriteria();        
        //$criteria->order = 'created_date DESC';
        $criteria->condition = 'user_id = ' . user()->id;
        
        $dataProvider = new CActiveDataProvider('WatchFullHistory', array(
            'criteria' => $criteria,
            'pagination' => array('pageSize' => 10)
        ));
        $this->render('watchFulllHistory', array('dataProvider' => $dataProvider));
    }
            
    public function actionPaymentHistory()
    {
        $criteria = new CDbCriteria();        
        //$criteria->order = 'created_date DESC';
        $criteria->condition = 'id_User = ' . user()->id;
        
        $dataProvider = new CActiveDataProvider('Paymenthistory', array(
            'criteria' => $criteria,
            'pagination' => array('pageSize' => 10)
        ));
        $this->render('paymentHistory', array('dataProvider' => $dataProvider));
    }
    
    public function actionBuyCredit()
    {
        $user = User::model()->findByPk(user()->id);
        
        if (isset($_GET['token'])) {
            $paypal = new Paypal();

            $params = array(
                'PAYERID' => $_GET['PayerID'],
                'TOKEN' => $_GET['token'],
                'CURRENCYCODE' => param('CURRENCY_CODE'),
                'PAYMENTACTION' => 'Sale',
                'AMT' => app()->session['amount'],
            );

            $response = $paypal->request('DoExpressCheckoutPayment', $params);
            
            if ($response['ACK'] == "Success") {
                $user->credit += intval(app()->session['amount'] / param('creditPrice'));
                if ($user->save()) {
                    app()->user->setFlash('success', 'Purchase Credit Successfull.');
                    $this->redirect(url('user/profile'));
                }
            } else
                Yii::log(json_encode ($response), CLogger::LEVEL_ERROR);
            
        }
        
        if (isset($_POST['credit'])) {
            $amount = number_format($_POST['credit'] * param('creditPrice'), 2);
            $paypal = new Paypal();
                        
            //Our request parameters
            $urls = array(
                'RETURNURL' => url('/user/buyCredit') . '/',
                'CANCELURL' => url('/shoppingCart/view') . '/',
            );

            $parrams = array(
                'PAYMENTACTION' => 'Sale',
                'AMT' => $amount,
                'CURRENCYCODE' => param('paypal', 'CURRENCY_CODE'),
            );

            $response = $paypal->request('SetExpressCheckout', $urls + $parrams);
           
            if (is_array($response) && $response['ACK'] == 'Success') { //Request successful
                $token = $response['TOKEN'];
                app()->session['amount'] = $amount;
                if (param('paypal', 'PAYPAL_IS_TEST'))
                    header('Location: https://www.sandbox.paypal.com/webscr?cmd=_express-checkout&token=' . urlencode($token));
                else
                    header('Location: https://www.paypal.com/webscr?cmd=_express-checkout&token=' . urlencode($token));
            } else
                app()->user->setFlash('error', "Paypal error: " . $response['L_LONGMESSAGE0'] );
        }
        
        $this->render('credit', array('user' => $user));
    }
    
    public function actionChangePassword()
    {        
        $model = new ChangePasswordForm();
        $user = User::model()->findByPk(user()->id);
        
         if (isset($_POST['ChangePasswordForm'])) {
            $model->attributes = $_POST['ChangePasswordForm'];
            if ($model->validate()) {
                $user->password = Utils::md5($model->new_password);
                if ($user->save(false)) {
                    Yii::app()->user->setFlash('success', 'Update profile successfully');
                    $this->refresh();
                }
            }
        }
        
        $this->render('changePassword',array('model' => $model));
    }

}

source/protected/apps/frontend/views/layouts/default/_search.php
<form id="mod-site-search" action="<?php echo url('/film/search') ?>" type="get" class="mod-search mod-search-autocomplete" name="search" role="search">
    <fieldset>
        <label for="search_field" class="access_aid">Search TV Movies</label>
        <input id="v" class="search_field mod-search-field" type="text" name="query" placeholder="Search TV &amp; Movies" autocomplete="off" value="<?php if (isset($_GET['query'])) echo $_GET['query'] ?>">
        <button type="submit" id="search_button" class="button search">
            <b></b>
            <span class="access_aid">Search</span>
        </button>
        <div class="mod-search-autocomplete-results"></div>
    </fieldset>
</form>

source/protected/apps/frontend/views/layouts/default/footer.php
<footer>
    <div role="contentinfo" class="footer">
        <div class="footer_top">
            <div class="footer_wrap">
                <dl class="parental">
                    <dt>
                    Parents:
                    </dt>
                    <dd>
                        <a >Parental Controls</a>
                    </dd>
                    <dd>
                        <a >Parental Resources</a>
                    </dd>
                </dl>
                <dl class="language">
                    <dt>
                    Change Language Preference to:
                    </dt>
                    <dd>
                        <a class="locale locale_es"  href="">Español</a>
                    </dd>
                </dl>
                <dl class="social">
                    <dt>
                    Follow Us:
                    </dt>
                    <dd>
                        <a target="_blank" class="icon facebook" ><span class="access_aid">Facebook</span></a>
                    </dd>
                    <dd>
                        <a target="_blank" class="icon twitter" ><span class="access_aid">Twitter</span></a>
                    </dd>
                    <dd>
                        <a >What to Watch Newsletters</a>
                    </dd>
                </dl>
            </div>
        </div>
        <div class="footer_wrap">
            <div class="footer_list ">
                <h6>XFINITY</h6>
                <ul>
                    <li>
                        <a href="" rel="default">Shop/Upgrade</a>
                    </li>
                    <li>
                        <a  rel="default">Mover's Edge</a>
                    </li>
                    <li>
                        <a  rel="default">XFINITY Bundles</a>
                    </li>
                    <li>
                        <a  rel="default">Comcast Business Class</a>
                    </li>
                    <li>
                        <a  rel="default">Home Security &amp; Control</a>
                    </li>
                    <li>
                        <a  rel="default">Customer Guarantee</a>
                    </li>
                </ul>
            </div>
            <div class="footer_list ">
                <h6>XFINITY TV</h6>
                <ul>
                    <li>
                        <a href="" rel="default">Shop/Upgrade</a>
                    </li>
                    <li>
                        <a  rel="default">Mover's Edge</a>
                    </li>
                    <li>
                        <a  rel="default">XFINITY Bundles</a>
                    </li>
                    <li>
                        <a  rel="default">Comcast Business Class</a>
                    </li>
                    <li>
                        <a  rel="default">Home Security &amp; Control</a>
                    </li>
                    <li>
                        <a  rel="default">Customer Guarantee</a>
                    </li>
                </ul>
            </div>
            <div class="footer_list ">
                <h6>XFINITY CONNECT</h6>
                <ul>
                    <li>
                        <a href="" rel="default">Shop/Upgrade</a>
                    </li>
                    <li>
                        <a  rel="default">Mover's Edge</a>
                    </li>
                    <li>
                        <a  rel="default">XFINITY Bundles</a>
                    </li>
                    <li>
                        <a  rel="default">Comcast Business Class</a>
                    </li>
                    <li>
                        <a  rel="default">Home Security &amp; Control</a>
                    </li>
                    <li>
                        <a  rel="default">Customer Guarantee</a>
                    </li>
                </ul>
            </div>
            <div class="footer_list ">
                <h6>Comcast Services</h6>
                <ul>
                    <li>
                        <a href="" rel="default">Shop/Upgrade</a>
                    </li>
                    <li>
                        <a  rel="default">Mover's Edge</a>
                    </li>
                    <li>
                        <a  rel="default">XFINITY Bundles</a>
                    </li>
                    <li>
                        <a  rel="default">Comcast Business Class</a>
                    </li>
                    <li>
                        <a  rel="default">Home Security &amp; Control</a>
                    </li>
                    <li>
                        <a  rel="default">Customer Guarantee</a>
                    </li>
                </ul>
            </div>
            <div class="footer_list last">
                <h6>Support  Information</h6>
                <ul>
                    <li>
                        <a  rel="default">XFINITY Learning Center</a>
                    </li>
                    <li>
                        <a  rel="default">Help FAQs</a>
                    </li>
                    <li>
                        <a  rel="default">Register a Comcast ID</a>
                    </li>
                    <li>
                        <a  rel="default">Create New Email Address</a>
                    </li>
                    <li>
                        <a rel="default">My Account</a>
                    </li>
                    <li>
                        <a rel="default">Pay My Bill</a>
                    </li>
                    <li>
                        <a href="" rel="default">[+] Submit Feedback</a>
                    </li>
                    <li>
                        <a href="" rel="default">Parental Resources</a>
                    </li>
                </ul>
            </div>
            <div class="footer_bot">
                <div class="icon logo_xfinity">
                    <span class="access_aid">XFINITY</span>
                </div>
                <ul>
                    <li class="first">
                        &copy; 2013 Comcast
                    </li>
                    <li>
                        <a href="" >Privacy Policy</a><span class="update">(Update)</span>
                    </li>
                    <li>
                        <a href="" id="adchoices">Ad Choices</a>
                    </li>
                    <li>
                        <a  href="">Terms of Service</a>
                    </li>
                    <li>
                        <a >Advertise with Us</a>
                    </li>
                    <li>
                        <a >Contact Us</a>
                    </li>
                </ul>
                <div class="icon logo_comcast">
                    <span class="access_aid">Comcast</span>
                </div>
                <ul class="legal">
                    <li>
                        &copy; 2013 Comcast Interactive Media, LLC. All Rights Reserved
                    </li>
                    <li>
                        2003 Bruce Glikas
                    </li>
                    <li>
                        &copy; 2004 ABC, INC.
                    </li>
                    <li>
                        &copy; 2004, Tommy Miyasaki for HGTV
                    </li>
                    <li>
                        &copy; 2006, Jack Parker for DIY Network
                    </li>
                    <li>
                        ABC
                    </li>
                    <li>
                        ABC Family
                    </li>
                    <li>
                        Andrew Eccles/The WB Television Network
                    </li>
                    <li>
                        Andrew MacPherson
                    </li>
                    <li>
                        Bob D'Amico
                    </li>
                    <li>
                        Cartoon Network
                    </li>
                    <li>
                        CBS
                    </li>
                    <li>
                        Chris Cuffaro/NBC
                    </li>
                    <li>
                        &copy; FOX (1193)
                    </li>
                    <li>
                        Evans Vestal Ward/Syfy
                    </li>
                    <li>
                        Fox
                    </li>
                    <li>
                        Frank Carroll/NBC
                    </li>
                    <li>
                        Getty Images
                    </li>
                    <li>
                        Nintendo/Cartoon Network
                    </li>
                    <li>
                        SCI FI Channel
                    </li>
                    <li>
                        Space Productions
                    </li>
                    <li>
                        THE CW
                    </li>
                    <li>
                        The N
                    </li>
                    <li>
                        The WB Television Network
                    </li>
                    <li class="last">
                        USA Network
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

source/protected/apps/frontend/views/layouts/default/header.php
<nav aria-label="Global Navigation" role="navigation" class="is-dark" id="cim-global-nav">
    <div class="cim-global-nav-wrapper">
        <div class="cim-global-nav-main">
            <ul role="menubar">
                <li role="menuitem">
                    <a title="Xfinity" href="<?php echo url('/') ?>" target="_top"  class="cim-global-nav-logo"> <b></b> </a>
                </li>
                <li class="is-active" role="menuitem">
                    <a title="TV" target="_blank" rel="external" > TV </a>
                </li>
                <li class="" role="menuitem">
                    <a title="Email" target="_blank" rel="external" > Email </a>
                </li>
                <li class="" role="menuitem">
                    <a title="Voicemail" target="_blank" rel="external" > Voicemail </a>
                </li>
                <li class="" role="menuitem">
                    <a title="Home Security" rel="default" > Home Security </a>
                </li>
                <li aria-haspopup="true" class="" role="menuitem">
                    <a title="More" target="_blank" rel="external" > More <b></b> </a>
                    <div class="sub-menu" aria-hidden="true">
                        <ul role="menu">
                            <li role="menuitem">
                                <a target="_blank" title="Money" > Money </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="News" > News </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Sports" > Sports </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Jobs" > Jobs </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Autos"> Autos </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Travel" > Travel </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Real Estate" > Real Estate </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Lifestyle" > Lifestyle </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Entertainment" > Entertainment </a>
                            </li>
                        </ul>
                        <ul role="menu">
                            <li role="menuitem">
                                <a target="_blank" title="TV Listings" > TV Listings </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Watchlist" > Watchlist </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="TV Shows" > TV Shows </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Movies" > Movies </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Streampix" > Streampix </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="Live TV" > Live TV </a>
                            </li>
                            <li role="menuitem">
                                <a target="_blank" title="DVR Manager" > DVR Manager </a>
                            </li>
                            <li role="menuitem">
                                <a data-cim-behavior="default" title="More..." > More... </a>
                            </li>
                        </ul>
                    </div>
                </li>
            </ul>

        </div>
        <div class="cim-global-nav-personal">
            <ul role="menubar">
                <li data-global-nav-item="ipauth" role="menuitem" aria-hidden="true">
                    <a  href="#"> <b class="font-icon-ipa-sm"></b> </a>
                </li>
                <li class="xp_shop_upgrade_link" role="menuitem">
                    <a title="Shop/Upgrade" > Shop/Upgrade </a>

                </li>
                <li class="xp_account_link" role="menuitem">
                    <a title="Profile" href="/user/profile">Profile</a>
                </li>
                <li class="xp_support_link" role="menuitem">
                    <a title="Buy Credit" href="/user/buyCredit">Buy Credit</a>
                </li>
                <li class="xp_signin has-username" role="menuitem">
                    <?php if (user()->isGuest) { ?>
                        <a title="Sign In" rel="signin" href="<?php echo url('/user/login') ?>"> Sign In</a>
                    <?php } else { ?>
                        <div class="username" class="hiden">
                            Hi <a title="Hi %s, My Profile" ><span></span></a>
                        </div>
                        <a title="Sign Out" rel="signout" href="<?php echo url('/user/logout') ?>"> Sign Out </a>
                    <?php } ?>
                </li>
            </ul>

        </div>

    </div>
</nav>
<!-- END NAV top -->

<nav class="mod-site-nav" role="navigation">
    <ul>
        <li data-nav-name="watch-online" class="nav-item is-active">
            <a title="Watch Online" href="index.htm" >Watch Online</a>
            <ul class="mod-site-subnav">
                <li data-subnav-name="tv-shows">
                    <a title="TV Shows" href="" >TV Shows</a>
                </li>
                <li data-subnav-name="movies">
                    <a title="Movies" href="movies.htm" >Movies</a>
                </li>
                <li data-subnav-name="family-&amp;-kids">
                    <a title="Family Kids" href="" >Family Kids</a>
                </li>
                <li data-subnav-name="networks">
                    <a title="Networks" href="" >Networks</a>
                </li>
                <li data-subnav-name="live-tv">
                    <a title="Live TV" href="" >Live TV</a>
                </li>
                <li data-subnav-name="streampix">
                    <a title="Streampix" href="" >Streampix</a>
                </li>
                <li data-subnav-name="latino">
                    <a title="Latino" href="" >Latino</a>
                </li>
            </ul>
        </li>
        <li data-nav-name="watch-on-tv" class="nav-item">
            <a title="Watch On TV" href="" >Watch On TV</a>
        </li>
        <li data-nav-name="saved" class="nav-item">
            <a title="Saved" href="" >Saved</a>
        </li>
        <li class="nav-item nav-item-queue">
            <a href="" >Watchlist</a>
        </li>
    </ul>
    <?php $this->renderPartial('/layouts/default/_search') ?>
</nav>
<!-- END nav -->

source/protected/apps/frontend/views/layouts/default/header_script.php
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/reset.css" type="text/css" media="all"/>
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/default.css" type="text/css" media="all"/>
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/xtv3_base.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/cmshome.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/xtv3_print.css" type="text/css" media="print" />
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/tools_rt.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/tools_rs.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/main.css" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/list.css" type="text/css" media="screen" />
<noscript>
<link rel="stylesheet" href="<?php echo app()->getBaseUrl()?>/css/noscript.css" type="text/css"/>
</noscript>